<?php
// Configure Session Security Settings
// https://www.php.net/manual/en/session.security.ini.php

// ! Mandatory
// Only use Cookies for Session ID management
// Prevents Session Fixation - where Session ID may be sent & read from a URL
ini_set("session.use_only_cookies", 1);

// ! Mandatory
// Only accept Session IDs generated by this website's server
ini_set("session.use_strict_mode", 1);

session_set_cookie_params([
  "lifetime" => 30 * 60, // calc 30 mins in seconds
  "domain" => "localhost",
  "path" => "/",
  "secure" => true, // HTTPS
  "httponly" => true, // prevent access on client-side (e.g. via JS)
  "samesite" => "Strict"
]);

// Init session
session_start();

// Regenerate Session ID every 30 mins
// This invalidates the Session ID of a user every 30 mins to minimise risk if 
// ...Session ID is somehow stolen/intercepted
if (!isset ($_SESSION["last_regen"])) {
  regenerateSessionId();
} else {
  $interval = 30 * 60;

  // Regenerate if the interval (in seconds) has passed since the last ID regeneration
  if (time() - $_SESSION["last_regen"] >= $interval) {
    regenerateSessionId();
  }
}

function regenerateSessionId() {
  session_regenerate_id(true); // Generates a more secure ID than session_start()
  $_SESSION["last_regen"] = time(); // track time of ID regeneration
}
